apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  labels:
    app: url-shortener
spec:
  replicas: 2 # Run 2 instances of your app for high availability
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: YOUR_ECR_REPO_URL/url-shortener-app:latest # Placeholder, updated by CI/CD
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-secrets # Name of Kubernetes Secret
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-secrets
              key: dbuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-secrets
              key: dbpassword
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-secrets
              key: dbhost # This will be the RDS endpoint
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-secrets
              key: dbport
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: url-shortener-db-secrets
              key: flask_secret_key
        livenessProbe: # Checks if the container is still running
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe: # Checks if the container is ready to serve traffic
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
